# Generated by Django 4.2.2 on 2023-08-21 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.CharField(max_length=50, null=True)),
                ('user', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao_Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, null=True)),
                ('data', models.CharField(max_length=50, null=True)),
                ('carteira', models.ManyToManyField(to='perfil.carteira')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.categoria')),
            ],
        ),
    ]
