# Generated by Django 4.2.2 on 2023-10-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_transacao_carteira_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='descricao',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='carteira',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
