# Generated by Django 4.2.2 on 2023-09-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carGest', '0003_remove_abastecimentos_carro_abastecimentos_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='matricula',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
