# Generated by Django 4.2.2 on 2023-09-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carGest', '0004_carro_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimentos',
            name='carro',
        ),
        migrations.AddField(
            model_name='abastecimentos',
            name='carro',
            field=models.ManyToManyField(to='carGest.carro'),
        ),
    ]
