# Generated by Django 4.2.2 on 2023-10-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carGest', '0005_remove_abastecimentos_carro_abastecimentos_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimentos',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
