# Generated by Django 4.2.2 on 2023-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carGest', '0006_alter_abastecimentos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimentos',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
